import type { Project } from './resume';

// Auto-generated by scripts/sync-github-projects.mjs.
// Curated projects in resume.ts take priority when GitHub URLs overlap.
export const githubProjects: Project[] = [
  {
    "title": "NYC Taxi Databricks",
    "category": "Data Engineering & Analytics",
    "github": "https://github.com/tuannm3812/NYC-Taxi-Databricks",
    "impact": "Databricks lakehouse analytics for NYC taxi trips",
    "stack": [
      "PySpark",
      "Databricks",
      "Delta Lake",
      "HTML"
    ],
    "points": [
      "Built a PySpark and Delta Lake workflow for NYC green and yellow taxi trip analytics.",
      "Auto-discovered from the public GitHub profile for portfolio review."
    ]
  },
  {
    "title": "Youtube Trending Snowflake Lakehouse",
    "category": "Data Engineering & Analytics",
    "github": "https://github.com/tuannm3812/youtube-trending-snowflake-lakehouse",
    "impact": "Snowflake pipeline for multi-country YouTube trends",
    "stack": [
      "Snowflake",
      "API",
      "Python"
    ],
    "points": [
      "Built a Snowflake workflow for ingesting, cleaning, and analyzing YouTube Trending data.",
      "Auto-discovered from the public GitHub profile for portfolio review."
    ]
  }
];
